@baseUrl = http://localhost:3001
@contentType = application/json

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsInZlcnNpb24iOjAsImlhdCI6MTU5MzYyNTQ1MywiZXhwIjoxNTk2MjE3NDUzfQ.Pj7KkPS8kxARJvy5z6aPUb6xraqT2_uu3gobQiOgF8Y
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsInZlcnNpb24iOjAsImlhdCI6MTU5MzYyNTk3MSwiZXhwIjoxNTk2MjE3OTcxfQ.rB4Q2cgoeyb2Rb8tlR_-xsQSjgNNaLgjOkHO5vUo6fI



###Create Account
POST {{baseUrl}}/auth/sign-up
Content-Type: {{contentType}}

{
  "email":"ryan19@gmail.com",
  "password":"12345",
  "password_confirmation": "12345"
}

###Login Account
POST  {{baseUrl}}/auth/sign-in
Content-Type: {{contentType}}

{
  "email":"ryan12@gmail.com",
  "password":"12345"
}

### Refrsh
POST  {{baseUrl}}/auth/refresh
Content-Type: {{contentType}}
Authorization: Bearer {{refreshToken}}

### List links
GET {{baseUrl}}/link
Content-Type: {{contentType}}
Authorization: Bearer {{token}}


### CREATE links
POST  {{baseUrl}}/link
Content-Type: {{contentType}}
Authorization: Bearer {{token}}


{
  "label": "Meu site445555",
  "url": "https://ryan.com",
  "isSocial": false
}

### Get a link by id
GET {{baseUrl}}/link/1
Content-Type: {{contentType}}


### EDITAR Link
PUT   {{baseUrl}}/link/1
Content-Type: {{contentType}}

{
  "label": "Meu novo site",
  "url": "www.facebook.com",
  "isSocial": true
}

### DELETE Link
DELETE    {{baseUrl}}/link/4
Content-Type: {{contentType}}
