@baseUrl = http://localhost:3001
@contentType = application/json

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNTkzNjA5Mjg0LCJleHAiOjE1OTM2MTEwODR9.HleB26pEJaJcuSkpASTZlY2x6fs7G_5mStwE-iiZSfI



###Create Account
POST {{baseUrl}}/auth/sign-up
Content-Type: {{contentType}}

{
  "email":"ryan@gmail.com",
  "password":"12345",
  "password_confirmation": "12345"
}

###Login Account
POST  {{baseUrl}}/auth/sign-in
Content-Type: {{contentType}}

{
  "email":"ryan@gmail.com",
  "password":"123456"
}

### List links
GET {{baseUrl}}/link
Content-Type: {{contentType}}
Authorization: Bearer {{token}}


### CREATE links
POST  {{baseUrl}}/link
Content-Type: {{contentType}}

{
  "label": "Meu site445555",
  "url": "https://ryan.com",
  "isSocial": false
}

### Get a link by id
GET {{baseUrl}}/link/1
Content-Type: {{contentType}}


### EDITAR Link
PUT   {{baseUrl}}/link/1
Content-Type: {{contentType}}

{
  "label": "Meu novo site",
  "url": "www.facebook.com",
  "isSocial": true
}

### DELETE Link
DELETE    {{baseUrl}}/link/4
Content-Type: {{contentType}}
